module.exports = {
  charges: {
    id: 'ch_1BHrh7EqomTNhbuDJwCsDyFE',
    object: 'charge',
    amount: 152400,
    amount_refunded: 0,
    application: null,
    application_fee: null,
    balance_transaction: 'txn_1BHcaxEqomTNhbuDCHAyNPP0',
    captured: true,
    created: 1509187057,
    currency: 'sek',
    customer: 'cus_BfC57M3FXEmV4s',
    description: null,
    destination: null,
    dispute: null,
    failure_code: null,
    failure_message: null,
    fraud_details: {},
    invoice: null,
    livemode: false,
    metadata: {},
    on_behalf_of: null,
    order: null,
    outcome: {
      network_status: 'approved_by_network',
      reason: null,
      seller_message: 'Payment complete.',
      type: 'authorized',
    },
    paid: true,
    receipt_email: 'Joesph40@hotmail.com',
    receipt_number: null,
    refunded: false,
    refunds: {
      object: 'list',
      data: [],
      has_more: false,
      total_count: 0,
      url: '/v1/charges/ch_1BHrh7EqomTNhbuDJwCsDyFE/refunds',
    },
    review: null,
    shipping: null,
    source: {
      id: 'card_1BHrh5EqomTNhbuDhYxehDdy',
      object: 'card',
      address_city: null,
      address_country: null,
      address_line1: null,
      address_line1_check: null,
      address_line2: null,
      address_state: null,
      address_zip: null,
      address_zip_check: null,
      brand: 'Visa',
      country: 'US',
      customer: 'cus_BfC57M3FXEmV4s',
      cvc_check: null,
      dynamic_last4: null,
      exp_month: 8,
      exp_year: 2019,
      fingerprint: 'zpphp2B6BE994eHh',
      funding: 'debit',
      last4: '5556',
      metadata: {},
      name: null,
      tokenization_method: null,
    },
    source_transfer: null,
    statement_descriptor: null,
    status: 'succeeded',
    transfer_group: null,
  },
  customers: {
    id: 'cus_BfDsNLoJwJ2aes',
    object: 'customer',
    account_balance: 0,
    created: 1509193727,
    currency: 'sek',
    default_source: null,
    delinquent: false,
    description: null,
    discount: null,
    email: null,
    livemode: false,
    metadata: {},
    shipping: null,
    sources: {
      object: 'list',
      data: [],
      has_more: false,
      total_count: 0,
      url: '/v1/customers/cus_BfDsNLoJwJ2aes/sources',
    },
    subscriptions: {
      object: 'list',
      data: [],
      has_more: false,
      total_count: 0,
      url: '/v1/customers/cus_BfDsNLoJwJ2aes/subscriptions',
    },
  },
};
